### ISSUE TITLE
它不支持umi2.2以上版本～！

### ISSUE THREAD

**Issue by zhilianbi520** [fattypanda/dva-model-persist#2]
不支持umi2.2版本～！

**Comment by fattypanda** [comment]
![image](https://user-images.githubusercontent.com/17585231/48181079-08933c80-e361-11e8-8b40-2344d43d917a.png)
![image](https://user-images.githubusercontent.com/17585231/48181098-19dc4900-e361-11e8-9f88-04bce41201d1.png)
![image](https://user-images.githubusercontent.com/17585231/48181135-47c18d80-e361-11e8-9ab9-db57ef17f952.png)
@zhilianbi520 我这里是可以使用的 umi@2.2.4 
PS：你这个头像是黑桐谷歌吗(@_@)

**Comment by zhilianbi520** [comment]
@fattypanda 试过了。。可以。多谢～！但是有一个问题，想请教下。。我将里面某个值例如：id:[] 修改成id:{} seesionstorage没更新到，但是如果id:null 修改成id:{} 这样就会更新到。。跟它的类型有关系嘛？只有匹配到数据类型不同才会更新？

**Comment by fattypanda** [comment]
这个我没尝试过，因为我平常都是定好默认的基础然后用  lodash/isEmpty 去判断，可能是 redux-persist 本身的问题，这个工具就是基于它开发的

**Comment by fattypanda** [comment]
@zhilianbi520

**Comment by fattypanda** [comment]
@zhilianbi520 或则你可以参考这个
[https://github.com/umijs/umi/issues/249](url)

**Comment by zhilianbi520** [comment]
> @zhilianbi520 或则你可以参考这个
> [https://github.com/umijs/umi/issues/249](url)
收到。多谢～！
